---
title: com.webos.service.ai.voice
date: 2020-11-09
weight: 80
toc: true
---
<div>
  <h2>API Summary</h2>
  <p>This service is used to recognize voice input.</p>
  <p>
    It can use and customize the configurations defined by the configuration
    (<strong>com.webos.service.config</strong>) API.
  </p>
</div>
<h2>Overview of the API</h2>
<div>
  <p>
    In webOS OSE, before using the <strong>ai.voice</strong> service, you need
    to set up Google Assistant on your device. The steps are detailed here:
  </p>
  <p><strong>Step A:&nbsp; Create credentials.json file.</strong></p>
  <ol>
    <li>​Create a Google account.&nbsp;</li>
    <li>
      Go to the
      <a href="https://console.actions.google.com/">Actions Console</a> and
      perform the following steps:
      <ol start="1">
        <li>Create a new project.</li>
        <li>
          Register your device model and download the OAuth-2.0 credentials
          file.&nbsp;(See
          <a href="http://developers.google.com/assistant/sdk/guides/service/python/embed/register-device">instructions</a>.)<br />
          <strong>Note:</strong>&nbsp;It is recommended that you select the
          device type as&nbsp;<strong>Auto</strong>&nbsp;to avoid errors during
          the setup.&nbsp;
        </li>
      </ol>
    </li>
    <li>
      After downloading the file,
      <ol start="1">
        <li>
          Move it from your local PC
          to&nbsp;<em>/etc/googleAssistant/client_secret.json</em>&nbsp;on your
          device using the command:​<br />
          $ scp &lt;downloaded json file&gt; root@&lt;your device
          ip&gt;:/etc/googleAssistant/client_secret.json&nbsp;
        </li>
        <li>
          From the device, run the following script:<br />
          $ cd /etc/googleAssistant<br />
          $ ./get_credentials.sh
        </li>
      </ol>
    </li>
    <li>Go to the URL generated by the above script. It provides some code.</li>
    <li>
      Copy the code and paste it on the device terminal and run the code. It
      creates the &#39;credentials.json&#39; file.&nbsp;
    </li>
    <li>
      Enable Google Assistant API, and configure the consent screen&nbsp;and
      activity controls for your project/account. (See
      <a href="https://developers.google.com/assistant/sdk/guides/service/python/embed/config-dev-project-and-account#config-dev-project">instructions</a>.)
    </li>
  </ol>
  <p><strong>Step B:&nbsp;Register the device ID.</strong></p>
  <ol>
    <li>
      Open device_id.json file.&nbsp;<br />
      $ cd /etc/googleAssistant<br />
      $ vi ./device_id.json
    </li>
    <li>
      Modify the fields:
      <ul>
        <li>
          id - Input the device instance string. Typically, &#39;my_webos&#39;.
        </li>
        <li>
          model_id -&nbsp; Input the device model ID registered in&nbsp;Step A.
        </li>
      </ul>
    </li>
    <li>
      Register the device using the command:<br />
      $ ./register_device_id.sh
    </li>
  </ol>
  <p>
    <strong>Step C:&nbsp;Input the device model and device ID for AI service.</strong>
  </p>
  <ol>
    <li>
      Enter the command:<br />
      $ vi /var/systemd/system/env/ai.env
    </li>
    <li>
      Modify the fields:
      <ul>
        <li>
          GOOGLEAI_DEVICE_MODEL - Input the device model ID registered in Step
          A.
        </li>
        <li>
          GOOGLEAI_DEVICE_ID - Input the device instance string registered in
          Step B.
        </li>
      </ul>
    </li>
  </ol>
  <p><strong>Step D:&nbsp;Reboot device or restart service daemon.</strong></p>
  <ul>
    <li>
      Enter the command:<br />
      $ reboot<br />
      OR,<br />
      $ systemctl restart ai
    </li>
  </ul>
  <p>
    <strong>Step E:&nbsp;Launch the service using the start() method.</strong>
  </p>
  <p>
    <strong>Note:&nbsp;</strong>Google assistant also supports&nbsp;<a href="https://developers.google.com/assistant/sdk/guides/service/python/extend/custom-actions" rel="nofollow">custom device actions</a>.
  </p>
  <ul>
    <li>
      For more information on the custom actions file, refer to
      /etc/googleAssistant/action.en.json.&nbsp;
    </li>
    <li>
      Requires the&nbsp;<a href="https://developers.google.com/actions/tools/gactions-cli">gactions CLI</a>
      tool.
    </li>
  </ul>
</div>
<h2>Methods</h2>
<div>
  <h3>start</h3>
  <div>
    <h4>Description</h4>
    <p>Starts the service based on the mode selected.</p>
    <p><strong>Note: </strong>This method is only for allowed clients.</p>
    <h4>Parameters</h4>
    <div class="table-container">
      <table class="table is-bordered is-fullwidth">
        <tbody>
          <tr>
            <th width="15%">
              <p>Name</p>
            </th>
            <th width="15%">
              <p>Required</p>
            </th>
            <th width="15%">
              <p>Type</p>
            </th>
            <th>
              <p>Description</p>
            </th>
          </tr>
          <tr>
            <td>mode</td>
            <td>Required</td>
            <td>String</td>
            <td>
              <p>Select the service mode. Possible values are:&nbsp;</p>
              <ul>
                <li>
                  <strong>continuous </strong>-&nbsp;The service will restart
                  automatically when a conversation ends.
                </li>
                <li>
                  <strong>single</strong> -&nbsp;The service will be stopped
                  when a conversation ends.
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td>keywordDetect</td>
            <td>Required</td>
            <td>Boolean</td>
            <td>
              <p>
                Indicates if a keyword is to be used for activating speech
                recognition. Possible values are:
              </p>
              <ul>
                <li>
                  <strong>true:&nbsp;</strong>Activated by a keyword. The
                  default keyword is &quot;Snowboy&quot;.&nbsp;<br />
                  To change the keyword model, refer&nbsp;<a href="https://snowboy.kitt.ai/" rel="nofollow">snowboy.kitt.ai</a>.&nbsp;<br />
                  Download custom the keyword model and move it to
                  <strong>/etc/googleAssistant/</strong> on your device. Then,
                  modify <strong>KEYWORD_DETECT_MODEL</strong> in
                  <strong>/var/systemd/system/env/ai.env</strong>.<br />
                  &nbsp;
                </li>
                <li>
                  <strong>false:&nbsp;</strong>Activated by a button press.
                </li>
              </ul>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <h4>Call Returns</h4>
    <div class="table-container">
      <table class="table is-bordered is-fullwidth">
        <tbody>
          <tr>
            <th width="15%">
              <p>Name</p>
            </th>
            <th width="15%">
              <p>Required</p>
            </th>
            <th width="15%">
              <p>Type</p>
            </th>
            <th>
              <p>Description</p>
            </th>
          </tr>
          <tr>
            <td>returnValue</td>
            <td>Required</td>
            <td>Boolean</td>
            <td>
              <p>Indicates the status of operation. Possible values are:</p>
              <ul>
                <li>
                  <strong>true&nbsp;</strong>- Indicates that the operation was
                  successful.
                </li>
                <li>
                  <strong>false&nbsp;</strong>- Indicates that the operation
                  failed. Check the&nbsp;&quot;errorCode&quot; and
                  &quot;errorText&quot; fields for details.
                </li>
              </ul>
            </td>
          </tr>
          <tr>
            <td>errorCode</td>
            <td>Optional</td>
            <td>Number (int8_t)</td>
            <td>
              <p>The error code for the failed operation.</p>
            </td>
          </tr>
          <tr>
            <td>errorText</td>
            <td>Optional</td>
            <td>String</td>
            <td>
              <p>
                Indicates the reason for the failure of the operation. See the
                &quot;<strong>API Error Codes Reference</strong>&quot; section
                for details.
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <h4>Example</h4>
    <div class="code-bg-grey">
      <p>
        # luna-send -n 1 -f luna://com.webos.service.ai.voice/start
        &#39;{&quot;mode&quot;: &quot;continuous&quot;,
        &quot;keywordDetect&quot;: true}&#39;
      </p>
      <p>&nbsp;</p>
      <p>Response:</p>
      <p>
        {&nbsp;&nbsp;<br />
        &nbsp;&nbsp;&nbsp;&quot;returnValue&quot;:true<br />
        }
      </p>
    </div>
  </div>
</div>
<h3>getState</h3>
<div>
  <h4>Description</h4>
  <p>
    Gets the current state of the service. It can have the following states:
  </p>
  <ul>
    <li><strong>idle</strong>: Before start.</li>
    <li><strong>waitActivation</strong>: Wait for keyword activation.</li>
    <li>
      <strong>recording</strong>: Uploading&nbsp;audio to the server&nbsp;for
      speech recognition.
    </li>
    <li><strong>thinking</strong>: Waiting for results from server.</li>
    <li>
      <strong>answering</strong>: Answering to the request&nbsp;through the
      speaker.
    </li>
  </ul>
  <p>
    {{< figure
    src="/images/docs/reference/com-webos-service-ai-voice-getState.png"
    alt="com.webos.service.ai.voice state diagram" height="150px" width="855px"
    >}}
  </p>
  <p>&nbsp;</p>
  <h4>Parameters</h4>
  <div class="table-container">
    <table class="table is-bordered is-fullwidth">
      <tbody>
        <tr>
          <th width="15%">
            <p>Name</p>
          </th>
          <th width="15%">
            <p>Required</p>
          </th>
          <th width="15%">
            <p>Type</p>
          </th>
          <th>
            <p>Description</p>
          </th>
        </tr>
        <tr>
          <td>subscribe</td>
          <td>Optional</td>
          <td>Boolean</td>
          <td>
            <p>Subscribe for notifications.&nbsp;Possible values are:</p>
            <ul>
              <li><strong>true&nbsp;</strong>- Get notifications.</li>
              <li>
                <strong>false&nbsp;</strong>- Notifications are not required.
              </li>
            </ul>
            <p>​<strong>Default value:</strong>&nbsp;false</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4>Call Returns</h4>
  <div class="table-container">
    <table class="table is-bordered is-fullwidth">
      <tbody>
        <tr>
          <th width="15%">
            <p>Name</p>
          </th>
          <th width="15%">
            <p>Required</p>
          </th>
          <th width="15%">
            <p>Type</p>
          </th>
          <th>
            <p>Description</p>
          </th>
        </tr>
        <tr>
          <td>returnValue</td>
          <td>Required</td>
          <td>String</td>
          <td>
            <p>Indicates the status of operation. Possible values are:</p>
            <ul>
              <li>
                <strong>true&nbsp;</strong>- Indicates that the operation was
                successful.
              </li>
              <li>
                <strong>false&nbsp;</strong>- Indicates that the operation
                failed. Check the&nbsp;&quot;errorCode&quot; and
                &quot;errorText&quot; fields for details.
              </li>
            </ul>
          </td>
        </tr>
        <tr>
          <td>subscribed</td>
          <td>Optional</td>
          <td>Boolean</td>
          <td>
            <p>
              Indicates if&nbsp;subscribed to get notified. Possible values are:
            </p>
            <ul>
              <li><strong>true&nbsp;</strong>- Get notifications</li>
              <li>
                <strong>false&nbsp;</strong>- Notifications are not required
              </li>
            </ul>
          </td>
        </tr>
        <tr>
          <td>state</td>
          <td>Required</td>
          <td>String</td>
          <td>
            <p>
              Indicates the running state of the service. Possible values are:
            </p>
            <ul>
              <li><strong>idle</strong></li>
              <li><strong>waitActivation</strong></li>
              <li><strong>recording</strong></li>
              <li><strong>thinking</strong></li>
              <li><strong>answering</strong></li>
            </ul>
          </td>
        </tr>
        <tr>
          <td>errorCode</td>
          <td>Optional</td>
          <td>Number (int8_t)</td>
          <td>
            <p>The error code for the failed operation.</p>
          </td>
        </tr>
        <tr>
          <td>errorText</td>
          <td>Optional</td>
          <td>String</td>
          <td>
            <p>
              Indicates the reason for the failure of the operation. See the
              &quot;<strong>API Error Codes Reference</strong>&quot; section for
              details.
            </p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4>Example</h4>
  <div class="code-bg-grey">
    <p>
      # luna-send -n 1 -f
      luna://com.webos.service.ai.voice/getState&nbsp;&#39;{}&#39;
    </p>
    <p>&nbsp;</p>
    <p>Response:</p>
    <p>
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;returnValue&quot;:true,<br />
      &nbsp;&nbsp;&nbsp;&quot;state&quot;:&quot;idle&quot;<br />
      }
    </p>
    <p>&nbsp;</p>
    <p>
      # luna-send -i&nbsp;-f
      luna://com.webos.service.ai.voice/getState&nbsp;&#39;{&quot;subscribe&quot;:
      true}&#39;
    </p>
    <p>&nbsp;</p>
    <p>Response:</p>
    <p>
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;returnValue&quot;:true,<br />
      &nbsp;&nbsp;&nbsp;&quot;state&quot;:&quot;idle&quot;<br />
      }<br />
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;state&quot;:&quot;waitActivation&quot;<br />
      }<br />
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;state&quot;:&quot;recording&quot;<br />
      }<br />
      ...
    </p>
  </div>
</div>
<h3>getResponse</h3>
<div>
  <h4>Description</h4>
  <p>Returns speech recognition results. This method is&nbsp;asynchronous.</p>
  <h4>Parameters</h4>
  <div class="table-container">
    <table class="table is-bordered is-fullwidth">
      <tbody>
        <tr>
          <th width="15%">
            <p>Name</p>
          </th>
          <th width="15%">
            <p>Required</p>
          </th>
          <th width="15%">
            <p>Type</p>
          </th>
          <th>
            <p>Description</p>
          </th>
        </tr>
        <tr>
          <td>subscribe</td>
          <td>Required</td>
          <td>Boolean</td>
          <td>
            <p>Subscribe for notifications.&nbsp;Possible values are:</p>
            <ul>
              <li><strong>true&nbsp;</strong>- Get notifications.</li>
              <li>
                <strong>false&nbsp;</strong>- Notifications are not required.
              </li>
            </ul>
            <p>​<strong>Default value:</strong>&nbsp;false</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4>Call Returns</h4>
  <div class="table-container">
    <table class="table is-bordered is-fullwidth">
      <tbody>
        <tr>
          <th width="15%">
            <p>Name</p>
          </th>
          <th width="15%">
            <p>Required</p>
          </th>
          <th width="15%">
            <p>Type</p>
          </th>
          <th>
            <p>Description</p>
          </th>
        </tr>
        <tr>
          <td>returnValue</td>
          <td>Required</td>
          <td>Boolean</td>
          <td>
            <p>Indicates the status of operation. Possible values are:</p>
            <ul>
              <li>
                <strong>true&nbsp;</strong>- Indicates that the operation was
                successful.
              </li>
              <li>
                <strong>false&nbsp;</strong>- Indicates that the operation
                failed. Check the&nbsp;&quot;errorCode&quot; and
                &quot;errorText&quot; fields for details.
              </li>
            </ul>
          </td>
        </tr>
        <tr>
          <td>subscribed</td>
          <td>Optional</td>
          <td>Boolean</td>
          <td>
            <p>
              Indicates if&nbsp;subscribed to get notified. Possible values are:
            </p>
            <ul>
              <li><strong>true&nbsp;</strong>- Get notifications.</li>
              <li>
                <strong>false&nbsp;</strong>- Notifications are not required​.
              </li>
            </ul>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4>Subscription Returns</h4>
  <div class="table-container">
    <table class="table is-bordered is-fullwidth">
      <tbody>
        <tr>
          <th width="15%">
            <p>Name</p>
          </th>
          <th width="15%">
            <p>Required</p>
          </th>
          <th width="15%">
            <p>Type</p>
          </th>
          <th>
            <p>Description</p>
          </th>
        </tr>
        <tr>
          <td>provider</td>
          <td>Optional</td>
          <td>String</td>
          <td>
            <p>
              Specifies the AI service provider that returns the results
              of&nbsp;speech recognition.
            </p>
            <p>
              In this case, it will always return &quot;googleassistant&quot;.
            </p>
          </td>
        </tr>
        <tr>
          <td>response</td>
          <td>Optional</td>
          <td>String</td>
          <td>
            <p>The results of speech recognition.</p>
            <p>Different providers will provide results in different format.</p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4>Example</h4>
  <div class="code-bg-grey">
    <p>Sample for webOS OSE users (when using googleassistant)</p>
    <p>
      # luna-send -i -f luna://com.webos.service.ai.voice/getResponse
      &#39;{&quot;subscribe&quot;: true}&#39;
    </p>
    <p>&nbsp;</p>
    <p>Response:</p>
    <p>
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;returnValue&quot;:true<br />
      }
    </p>
    <p>&nbsp;</p>
    <p>Googleassistant for webOS OSE case:</p>
    <p>Example subscribe for Trigger Word Detection:</p>
    <p>
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;provider&quot;:&quot;googleassistant&quot;,<br />
      &nbsp;&nbsp;&nbsp;&quot;response&quot;:{&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;keywordDetected&quot;:1<br />
      &nbsp;&nbsp;&nbsp;}<br />
      }
    </p>
    <p>&nbsp;</p>
    <p>Example subscribe for Automatic Speech Recognition:</p>
    <p>
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;provider&quot;:&quot;googleassistant&quot;,<br />
      &nbsp;&nbsp;&nbsp;&quot;response&quot;:{&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;partial&quot;:&quot;what&quot;<br />
      &nbsp;&nbsp;&nbsp;}<br />
      }<br />
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;provider&quot;:&quot;googleassistant&quot;,<br />
      &nbsp;&nbsp;&nbsp;&quot;response&quot;:{&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;partial&quot;:&quot;what&#39;s&quot;<br />
      &nbsp;&nbsp;&nbsp;}<br />
      }<br />
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;provider&quot;:&quot;googleassistant&quot;,<br />
      &nbsp;&nbsp;&nbsp;&quot;response&quot;:{&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;partial&quot;:&quot;what&#39;s&nbsp;the&quot;<br />
      &nbsp;&nbsp;&nbsp;}<br />
      }<br />
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;provider&quot;:&quot;googleassistant&quot;,<br />
      &nbsp;&nbsp;&nbsp;&quot;response&quot;:{&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;partial&quot;:&quot;what&#39;s&nbsp;the&nbsp;weather&quot;<br />
      &nbsp;&nbsp;&nbsp;}<br />
      }<br />
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;provider&quot;:&quot;googleassistant&quot;,<br />
      &nbsp;&nbsp;&nbsp;&quot;response&quot;:{&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;displayText&quot;:&quot;It&nbsp;looks&nbsp;pleasant&nbsp;outside&nbsp;Currently&nbsp;in&nbsp;Seoul&nbsp;it&#39;s&nbsp;79&nbsp;and&nbsp;partly&nbsp;cloudy.&nbsp;The&nbsp;forecast&nbsp;today&nbsp;is&nbsp;78&nbsp;and&nbsp;mostly&nbsp;cloudy.&nbsp;(&nbsp;More&nbsp;on&nbsp;weather.com&nbsp;)&quot;<br />
      &nbsp;&nbsp;&nbsp;}<br />
      }
    </p>
  </div>
</div>
<h3>stop</h3>
<div>
  <h4>Description</h4>
  <p>
    Stops&nbsp;the service. Make sure to call this method before starting
    another engine.
  </p>
  <p><strong>Note: </strong>This method is only for allowed clients.</p>
  <h4>Parameters</h4>
  <p>None</p>
  <h4>Call Returns</h4>
  <div class="table-container">
    <table class="table is-bordered is-fullwidth">
      <tbody>
        <tr>
          <th width="15%">
            <p>Name</p>
          </th>
          <th width="15%">
            <p>Required</p>
          </th>
          <th width="15%">
            <p>Type</p>
          </th>
          <th>
            <p>Description</p>
          </th>
        </tr>
        <tr>
          <td>returnValue</td>
          <td>Required</td>
          <td>Boolean</td>
          <td>
            <p>Indicates the status of operation. Possible values are:</p>
            <ul>
              <li>
                <strong>true&nbsp;</strong>- Indicates that the operation was
                successful.
              </li>
              <li>
                <strong>false&nbsp;</strong>- Indicates that the operation
                failed. Check the&nbsp;&quot;errorCode&quot; and
                &quot;errorText&quot; fields for details.
              </li>
            </ul>
          </td>
        </tr>
        <tr>
          <td>errorCode</td>
          <td>Optional</td>
          <td>Number (int8_t)</td>
          <td>
            <p>The error code for the failed operation.</p>
          </td>
        </tr>
        <tr>
          <td>errorText</td>
          <td>Optional</td>
          <td>String</td>
          <td>
            <p>
              Indicates the reason for the failure of the operation. See the
              &quot;<strong>API Error Codes Reference</strong>&quot; section for
              details.
            </p>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <h4>Example</h4>
  <div class="code-bg-grey">
    <p>
      # luna-send -n 1 -f
      luna://com.webos.service.ai.voice/stop&nbsp;&#39;{}&#39;
    </p>
    <p>&nbsp;</p>
    <p>Response:</p>
    <p>
      {&nbsp;&nbsp;<br />
      &nbsp;&nbsp;&nbsp;&quot;returnValue&quot;:true<br />
      }
    </p>
  </div>
</div>
<h2>API Error Codes Reference</h2>
<div class="table-container">
  <table class="table is-bordered is-fullwidth">
    <tbody>
      <tr>
        <th width="15%">
          <p>Error Code</p>
        </th>
        <th width="30%">
          <p>Error Text</p>
        </th>
        <th width="55%">
          <p>Error Description</p>
        </th>
      </tr>
      <tr>
        <td>0</td>
        <td>Not error</td>
        <td>
          <p>Not error.</p>
        </td>
      </tr>
      <tr>
        <td>-1</td>
        <td>Unknown error</td>
        <td>
          <p>Unknown error.</p>
        </td>
      </tr>
      <tr>
        <td>-2</td>
        <td>Invalid parameters</td>
        <td>
          <p>This error occurs&nbsp;when api parameters are incorrectly.</p>
        </td>
      </tr>
      <tr>
        <td>-3</td>
        <td>Invalid configurations</td>
        <td>
          <p>
            This error occurs&nbsp;when system missed the environment files.
          </p>
        </td>
      </tr>
      <tr>
        <td>-5</td>
        <td>Network error has occurred</td>
        <td>
          <p>Network error has occurred.</p>
        </td>
      </tr>
      <tr>
        <td>-6</td>
        <td>Not supported</td>
        <td>
          <p>Not supported api.</p>
        </td>
      </tr>
      <tr>
        <td>-7</td>
        <td>Service had not started</td>
        <td>
          <p>Service had not started.</p>
        </td>
      </tr>
      <tr>
        <td>-8</td>
        <td>Service had already started</td>
        <td>
          <p>Service had already started.</p>
        </td>
      </tr>
      <tr>
        <td>-9</td>
        <td>Microphone error has occurred</td>
        <td>
          <p>Microphone error has occurred.</p>
        </td>
      </tr>
      <tr>
        <td>-10</td>
        <td>Audio error has occurred</td>
        <td>
          <p>Audio&nbsp;error has occurred.</p>
        </td>
      </tr>
      <tr>
        <td>-11</td>
        <td>Camera error has occurred</td>
        <td>
          <p>Camera error has occurred.</p>
        </td>
      </tr>
    </tbody>
  </table>
</div>
